variable "instance_count" {}
variable "public_ip_name" {}
variable "location" {}
variable "resource_group_name" {}
variable "nic_name" {}
variable "nsg_id" {}
variable "ip_config_name" {}
variable "subnet_id" {}
variable "vm_name" {}
variable "vm_size" {}
variable "availability_set_id" {}
variable "vm_os_disk_size_in_gb" {}
variable "os_publisher" {}
variable "os_offer" {}
variable "os_sku" {}
variable "os_version" {}
variable "vm_admin_username" {}
variable "vm_admin_password" {}
variable "assign_public_ip" {}